LICHEE_CHIP:=sun50iw6p1
LICHEE_ARCH:=arm64
LICHEE_BRANDY_VER:=1.0
LICHEE_KERN_VER:=4.9
LICHEE_KERN_DEFCONF:=sun50iw6p1smp_defconfig
LICHEE_BUILDING_SYSTEM:=buildroot
LICHEE_BR_VER:=201611
LICHEE_BR_DEFCONF:=sun8i_defconfig
